name: semasync_new
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10+1
  fl_chart: ^0.68.0
  percent_indicator: ^4.2.3
  lottie: ^3.1.0
  shimmer: ^3.0.0

  # State Management
  provider: ^6.1.2

  # Utils
  intl: ^0.19.0
  image_picker: ^1.0.7
  camera: ^0.10.5+9
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2

  # Food Scanning
  mobile_scanner: ^7.1.2
  image: ^4.1.7
  google_mlkit_image_labeling: ^0.14.1
  google_mlkit_commons: ^0.11.0

  # HTTP and API
  http: ^1.1.0
  dio: ^5.4.0

  # Charts and Visualization
  syncfusion_flutter_charts: ^25.1.35
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
