services:
  - type: web
    name: semasync-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 24h
      - key: JWT_REFRESH_EXPIRE
        value: 7d
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: PASSWORD_RESET_EXPIRE
        value: 3600000
    # Add these manually in Render dashboard:
    # MONGODB_URI=mongodb+srv://username:password@cluster.mongodb.net/semasync
    # EMAIL_HOST=smtp.gmail.com
    # EMAIL_PORT=587
    # EMAIL_USER=your-email@gmail.com
    # EMAIL_PASS=your-app-password
    # CLIENT_URL=https://your-frontend-domain.com
